### ISSUE TITLE
mac osx 10.11.4 : build fails

### ISSUE THREAD

**Issue by schnerchi** [monero-project/bitmonero#750]
After updating to 10.11.4 yesterday the build fails... 10.11.3 worked yesterday :

Desktop/Dev/bitmonero/contrib/epee/include/storages/portable_storage_template_helper.h:75:14: error: 
      moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
      return std::move(json_buff);
             ^
Desktop/Dev/bitmonero/contrib/epee/include/storages/portable_storage_template_helper.h:75:14: note: 
      remove std::move call here
      return std::move(json_buff);
             ^~~~~~~~~~         ~
Desktop/Dev/bitmonero/contrib/epee/include/storages/portable_storage_template_helper.h:120:14: error: 
      moving a local object in a return statement prevents copy elision [-Werror,-Wpessimizing-move]
      return std::move(binary_buff);
             ^
Desktop/Dev/bitmonero/contrib/epee/include/storages/portable_storage_template_helper.h:120:14: note: 
      remove std::move call here
      return std::move(binary_buff);
             ^~~~~~~~~~           ~

**Comment by antanst** [comment]
Same on my Mac.

**Comment by fluffypony** [comment]
Fixed - pull latest from github and try again:)
