### ISSUE TITLE
Linux 32-bit builds no-worky

### ISSUE THREAD

**Issue by fluffypony** [monero-project/bitmonero#103]
@dbit34 couldn't compile on an Ubuntu 12.04 32-bit VirtualBox, got this error:

````
[ 37%] Building CXX object src/CMakeFiles/cryptonote_core.dir/cryptonote_core/difficulty.cpp.o
/home/david/Monero/bitmonero/src/cryptonote_core/difficulty.cpp: In function ‘void cryptonote::mul(uint64_t, uint64_t, uint64_t&, uint64_t&)’:
/home/david/Monero/bitmonero/src/cryptonote_core/difficulty.cpp:59:22: error: expected unqualified-id before ‘__int128’
     typedef unsigned __int128 uint128_t;
                      ^
/home/david/Monero/bitmonero/src/cryptonote_core/difficulty.cpp:60:5: error: ‘uint128_t’ was not declared in this scope
     uint128_t res = (uint128_t) a * (uint128_t) b;
     ^
/home/david/Monero/bitmonero/src/cryptonote_core/difficulty.cpp:60:15: error: expected ‘;’ before ‘res’
     uint128_t res = (uint128_t) a * (uint128_t) b;
               ^
/home/david/Monero/bitmonero/src/cryptonote_core/difficulty.cpp:61:22: error: ‘res’ was not declared in this scope
     low = (uint64_t) res;
                      ^
make[3]: *** [src/CMakeFiles/cryptonote_core.dir/cryptonote_core/difficulty.cpp.o] Error 1
make[3]: Leaving directory `/home/david/Monero/bitmonero/build/release'
make[2]: *** [src/CMakeFiles/cryptonote_core.dir/all] Error 2
make[2]: Leaving directory `/home/david/Monero/bitmonero/build/release'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/david/Monero/bitmonero/build/release'
make: *** [build-release] Error 2
````

If we're supporting 32-bit Windows builds we should support 32-bit Linux builds. VERY low priority.

**Comment by iPerky** [comment]
Will 32 bit linux be supported in the future?

```
Linux legs 2.6.32-042stab093.4 #1 SMP Mon Aug 11 18:47:39 MSK 2014 i686 i686 i686 GNU/Linux
```

```
/home/ihashfury/tmp/bitmonero/src/crypto/slow-hash.c:558:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     U64(b)[1] = U64(&state.k[16])[1] ^ U64(&state.k[48])[1];
     ^
/home/ihashfury/tmp/bitmonero/src/crypto/slow-hash.c:558:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
/home/ihashfury/tmp/bitmonero/src/crypto/slow-hash.c:573:16: error: incompatible types when assigning to type '__m128i' from type 'int'
             _c = _mm_aesenc_si128(_c, _a);
                ^
cc1: all warnings being treated as errors
make[3]: *** [src/crypto/CMakeFiles/crypto.dir/slow-hash.c.o] Error 1
make[3]: Leaving directory `/home/ihashfury/tmp/bitmonero/build/release'
make[2]: *** [src/crypto/CMakeFiles/crypto.dir/all] Error 2
make[2]: Leaving directory `/home/ihashfury/tmp/bitmonero/build/release'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/home/ihashfury/tmp/bitmonero/build/release'
make: *** [release-all] Error 2
```

**Comment by fluffypony** [comment]
@iPerky yes, we've been working on that and ARM for Linux, so definitely:)

**Comment by iPerky** [comment]
I have a full node syncing on archlinuxarm (cubox-i4) - builds and runs well - but takes ages to sync.

Just spun up 64bit VPS instead - should have two full nodes running soon

**Comment by fluffypony** [comment]
Fixed
