### ISSUE TITLE
static build of tests fails with `undefined reference to __wrap___cxa_throw`

### ISSUE THREAD

**Issue by radfish** [monero-project/bitmonero#926]
Debian Jessie x86_64 *without* libunwind-dev and libunwind8 (otherwise fails due to #907). Same on Arch Linux 32-bit and 64-bit, too.
[build.log.txt](https://github.com/monero-project/bitmonero/files/379937/build.log.txt)

```
cmake -DCMAKE_BUILD_TYPE=Release -DSTATIC=ON -DBUILD_TESTS=ON .. 2>&1 | tee -a build.log
```
```
/tmp/cc8lNtqY.ltrans12.ltrans.o: In function `boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::thread_resource_error> >::rethrow() const [clone .lto_priv.41]':
cc8lNtqY.ltrans12.o:(.text+0x4e): undefined reference to `__wrap___cxa_throw'
```

Build succeeds with `BUILD_TESTS=OFF`

**Comment by radfish** [comment]
Fixed by #933
