### ISSUE TITLE
chaingen_main.cpp fails to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by iamsmooth** [monero-project/bitmonero#739]
Pretty sure this worked until recently

In file included from /home/ubuntu/github/bitmonero/tests/core_tests/chaingen_main.cpp:31:0:
/home/ubuntu/github/bitmonero/tests/core_tests/chaingen.h: In instantiation of ‘bool do_replay_events(std::vector<boost::variant<cryptonote::block, cryptonote::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visitor_settings> >&) [with t_test_class = gen_simple_chain_001]’:
/home/ubuntu/github/bitmonero/tests/core_tests/chaingen_main.cpp:97:5:   required from here
/home/ubuntu/github/bitmonero/tests/core_tests/chaingen.h:474:8: error: invalid initializer for array member ‘const std::pair<unsigned char, long unsigned int> get_test_options<gen_simple_chain_001>::hard_forks [1]’
 struct get_test_options {
        ^

many more lines of error output follow

**Comment by iamsmooth** [comment]
Changing line 475 to this fixes it: 

  const std::pair<uint8_t, uint64_t> hard_forks[1] = {std::make_pair((uint8_t)1, (uint64_t)0)};

**Comment by iamsmooth** [comment]
correction, still broken

**Comment by laanwj** [comment]
Same problem here w/ master eb1b87d2393f34caa9698bec23a4b78fa57da752
```
[ 80%] Building CXX object tests/core_tests/CMakeFiles/coretests.dir/chaingen_main.cpp.o
In file included from /home/ubuntu/bitmonero/tests/core_tests/chaingen_main.cpp:31:0:
/home/ubuntu/bitmonero/tests/core_tests/chaingen.h: In instantiation of ‘bool do_replay_events(std::vector<boost::variant<cryptonote::block, cryptonote
::transaction, cryptonote::account_base, callback_entry, serialized_object<cryptonote::block>, serialized_object<cryptonote::transaction>, event_visito
r_settings> >&) [with t_test_class = gen_simple_chain_001]’:
/home/ubuntu/bitmonero/tests/core_tests/chaingen_main.cpp:97:5:   required from here
/home/ubuntu/bitmonero/tests/core_tests/chaingen.h:474:8: error: invalid initializer for array member ‘const std::pair<unsigned char, long unsigned int
> get_test_options<gen_simple_chain_001>::hard_forks [1]’
 struct get_test_options {
        ^
/home/ubuntu/bitmonero/tests/core_tests/chaingen.h:500:34: note: synthesized method ‘constexpr get_test_options<gen_simple_chain_001>::get_test_options
()’ first required here 
   get_test_options<t_test_class> gto;
```

**Comment by iamsmooth** [comment]
This substitute compiles. Not tested

struct get_test_options {
  const std::pair<uint8_t, uint64_t> hard_forks[1];
  const cryptonote::test_options test_options = {
    hard_forks
  };
get_test_options():hard_forks{std::make_pair((uint8_t)1, (uint64_t)0)}{}
};

**Comment by moneromooo-monero** [comment]
Passes tests.

**Comment by p4fg** [comment]
Any news on when this might be fixed in master?

**Comment by moneromooo-monero** [comment]
https://github.com/monero-project/bitmonero/pull/788

**Comment by fluffypony** [comment]
Fixed
